joy_teleop:
  ros__parameters:
    joy_config: 'xbox'
    publish_stamped_twist: true
    move:
      type: topic
      interface_type: geometry_msgs/msg/TwistStamped
      topic_name: tamiyabot_controller/reference
      deadman_buttons: [5]
      axis_mappings:
        linear-x:
          axis: 1
          scale: 1.0
          offset: 0.0
        angular-z:
          axis: 3
          scale: 1.0
          offset: 0.0
