controller_manager:
  ros__parameters:
    update_rate: 30 # Hz
    use_sim_time: true

    tamiyabot_controller:
      type: ackermann_steering_controller/AckermannSteeringController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

tamiyabot_controller:
  ros__parameters:
      type: 'ackermann_steering_controller/AckermannSteeringController'
      wheelbase: 0.28
      front_wheel_track: 0.14
      rear_wheel_track: 0.14
      front_wheels_radius: 0.0415
      rear_wheels_radius: 0.0415
      front_steering: true
      reference_timeout: 2.0
      rear_wheels_names: ['rear_left_wheel_joint', 'rear_right_wheel_joint']
      front_wheels_names: ['front_left_steering_joint', 'front_right_steering_joint']
      open_loop: false
      velocity_rolling_window_size: 10
      base_frame_id: base_link
      odom_frame_id: odom
      enable_odom_tf: true
      twist_covariance_diagonal: [0.0, 7.0, 14.0, 21.0, 28.0, 35.0]
      pose_covariance_diagonal: [0.0, 7.0, 14.0, 21.0, 28.0, 35.0]
      position_feedback: false
