controller_manager:
  ros__parameters:
    update_rate: 30 # Hz
    use_sim_time: true

    tamiyabot_controller:
      type: ackermann_steering_controller/AckermannSteeringController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

tamiyabot_controller:
  ros__parameters:
    reference_timeout: 2.0
    front_steering: true
    open_loop: false
    velocity_rolling_window_size: 10
    position_feedback: true
    use_stamped_vel: false   
    
    rear_wheels_names   : ['rear_right_wheel_joint', 'rear_left_wheel_joint']
    front_wheels_names  : ['front_right_steering_joint', 'front_left_steering_joint']

    wheelbase         : 0.28
    front_wheel_track : 0.14
    rear_wheel_track  : 0.14
    front_wheels_radius  : 0.0415
    rear_wheels_radius   : 0.0415
